require "faraday"
require "json"
require "ostruct"
require "spotify/version"

module Spotify
  autoload :Error, "spotify/error"
  autoload :Errors, "spotify/error_generator"
  autoload :ErrorGenerator, "spotify/error_generator"
  autoload :ErrorFactory, "spotify/error_generator"

  autoload :Client, "spotify/client"
  autoload :Collection, "spotify/collection"
  autoload :Resource, "spotify/resource"
  autoload :Object, "spotify/object"

  autoload :MeResource, "spotify/resources/me"
  autoload :SearchResource, "spotify/resources/search"
  autoload :PlayerResource, "spotify/resources/player"
  autoload :UsersResource, "spotify/resources/users"
  autoload :AlbumsResource, "spotify/resources/albums"
  autoload :ArtistsResource, "spotify/resources/artists"
  autoload :PlaylistsResource, "spotify/resources/playlists"
  autoload :TracksResource, "spotify/resources/tracks"

  autoload :User, "spotify/objects/user"
  autoload :Album, "spotify/objects/album"
  autoload :Track, "spotify/objects/track"
  autoload :Artist, "spotify/objects/artist"
  autoload :Audiobook, "spotify/objects/audiobook"
  autoload :Episode, "spotify/objects/episode"
  autoload :Playlist, "spotify/objects/playlist"
  autoload :Show, "spotify/objects/show"
  autoload :Snapshot, "spotify/objects/snapshot"
  autoload :Player, "spotify/objects/player"
  autoload :Device, "spotify/objects/device"
end
