require "faraday"
require "json"
require "ostruct"
require "spotify/version"

module Spotify
  autoload :Error, "spotify/error"
  autoload :Errors, "spotify/error_generator"
  autoload :ErrorGenerator, "spotify/error_generator"
  autoload :ErrorFactory, "spotify/error_generator"

  autoload :Client, "spotify/client"
  autoload :Collection, "spotify/collection"
  autoload :Resource, "spotify/resource"
  autoload :Object, "spotify/object"

  # autoload :OAuth, "spotify/oauth"


  autoload :UsersResource, "spotify/resources/users"
  # autoload :ChannelsResource, "spotify/resources/channels"
  # autoload :EmotesResource, "spotify/resources/emotes"
  # autoload :BadgesResource, "spotify/resources/badges"
  # autoload :GamesResource, "spotify/resources/games"
  # autoload :VideosResource, "spotify/resources/videos"
  # autoload :ClipsResource, "spotify/resources/clips"
  # autoload :EventsubSubscriptionsResource, "spotify/resources/eventsub_subscriptions"
  # autoload :EventsubConduitsResource, "spotify/resources/eventsub_conduits"
  # autoload :BannedEventsResource, "spotify/resources/banned_events"
  # autoload :BannedUsersResource, "spotify/resources/banned_users"
  # autoload :ModeratorsResource, "spotify/resources/moderators"
  # autoload :ModeratorEventsResource, "spotify/resources/moderator_events"
  # autoload :PollsResource, "spotify/resources/polls"
  # autoload :PredictionsResource, "spotify/resources/predictions"
  # autoload :StreamScheduleResource, "spotify/resources/stream_schedule"
  # autoload :SearchResource, "spotify/resources/search"
  # autoload :StreamsResource, "spotify/resources/streams"
  # autoload :StreamMarkersResource, "spotify/resources/stream_markers"
  # autoload :SubscriptionsResource, "spotify/resources/subscriptions"
  # autoload :TagsResource, "spotify/resources/tags"
  # autoload :CustomRewardsResource, "spotify/resources/custom_rewards"
  # autoload :CustomRewardRedemptionsResource, "spotify/resources/custom_reward_redemptions"
  # autoload :GoalsResource, "spotify/resources/goals"
  # autoload :HypeTrainEventsResource, "spotify/resources/hype_train_events"
  # autoload :AnnouncementsResource, "spotify/resources/announcements"
  # autoload :RaidsResource, "spotify/resources/raids"
  # autoload :ChatMessagesResource, "spotify/resources/chat_messages"
  # autoload :VipsResource, "spotify/resources/vips"
  # autoload :WhispersResource, "spotify/resources/whispers"
  # autoload :AutomodResource, "spotify/resources/automod"
  # autoload :BlockedTermsResource, "spotify/resources/blocked_terms"
  # autoload :CharityCampaignsResource, "spotify/resources/charity_campaigns"
  # autoload :ChattersResource, "spotify/resources/chatters"
  # autoload :ShoutoutsResource, "spotify/resources/shoutouts"
  # autoload :UnbanRequestsResource, "spotify/resources/unban_requests"
  # autoload :WarningsResource, "spotify/resources/warnings"


  autoload :User, "spotify/objects/user"
  # autoload :FollowedUser, "spotify/objects/followed_user"
  # autoload :BlockedUser, "spotify/objects/blocked_user"

  # autoload :Channel, "spotify/objects/channel"
  # autoload :ChannelEditor, "spotify/objects/channel_editor"
  # autoload :Emote, "spotify/objects/emote"
  # autoload :Badge, "spotify/objects/badge"
  # autoload :Game, "spotify/objects/game"
  # autoload :Video, "spotify/objects/video"
  # autoload :Clip, "spotify/objects/clip"
  # autoload :EventsubSubscription, "spotify/objects/eventsub_subscription"
  # autoload :EventsubConduit, "spotify/objects/eventsub_conduit"
  # autoload :EventsubConduitShard, "spotify/objects/eventsub_conduit_shard"
  # autoload :BannedEvent, "spotify/objects/banned_event"
  # autoload :BannedUser, "spotify/objects/banned_user"
  # autoload :Moderator, "spotify/objects/moderator"
  # autoload :ModeratorEvent, "spotify/objects/moderator_event"
  # autoload :Poll, "spotify/objects/poll"
  # autoload :Prediction, "spotify/objects/prediction"
  # autoload :StreamSchedule, "spotify/objects/stream_schedule"
  # autoload :SearchResult, "spotify/objects/search_result"
  # autoload :Stream, "spotify/objects/stream"
  # autoload :StreamMarker, "spotify/objects/stream_marker"
  # autoload :Subscription, "spotify/objects/subscription"
  # autoload :SubscriptionCount, "spotify/objects/subscription_count"
  # autoload :Tag, "spotify/objects/tag"
  # autoload :CustomReward, "spotify/objects/custom_reward"
  # autoload :CustomRewardRedemption, "spotify/objects/custom_reward_redemption"
  # autoload :Goal, "spotify/objects/goal"
  # autoload :HypeTrainEvent, "spotify/objects/hype_train_event"
  # autoload :FollowCount, "spotify/objects/follow_count"
  # autoload :Raid, "spotify/objects/raid"
  # autoload :UserColor, "spotify/objects/user_color"
  # autoload :Vip, "spotify/objects/vip"
  # autoload :AutomodStatus, "spotify/objects/automod_status"
  # autoload :AutomodSetting, "spotify/objects/automod_setting"
  # autoload :BlockedTerm, "spotify/objects/blocked_term"
  # autoload :CharityCampaign, "spotify/objects/charity_campaign"
  # autoload :Chatter, "spotify/objects/chatter"
  # autoload :ChatMessage, "spotify/objects/chat_message"
  # autoload :UnbanRequest, "spotify/objects/unban_request"
  # autoload :Warning, "spotify/objects/warning"
end
